#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: Payal Kushwaha | Registration: [24BCE11392]
# Course: Open Source Software | VIT Bhopal
# Description: Interactively asks the user three questions,
#              then composes a personalised open-source
#              philosophy statement and saves it to a .txt file.
# Concepts: read, string concatenation, file I/O (>), date,
#           aliases (demonstrated below as a comment example)
# ============================================================

# --- Alias concept (demonstration via comment) ---
# In a live shell session, you could define:
#   alias show_manifesto='cat manifesto_$(whoami).txt'
# Aliases let you create shorthand for frequently used commands.
# They are defined in ~/.bashrc for persistence across sessions.
# We simulate this concept here using a variable for the output path.

# --- Output file path ---
# Using the current username in the filename makes it unique
OUTPUT="manifesto_$(whoami).txt"

# --- Display intro banner ---
echo "=============================================================="
echo "  OPEN SOURCE MANIFESTO GENERATOR"
echo "  VIT Bhopal | Open Source Software Course"
echo "=============================================================="
echo ""
echo "  Answer three questions honestly."
echo "  Your responses will shape a personal open-source manifesto."
echo "  This manifesto will be saved as: $OUTPUT"
echo ""
echo "--------------------------------------------------------------"

# --- Question 1: Daily open-source tool ---
# 'read -p' displays a prompt and waits for user input
read -p "  1. Name one open-source tool you use every day: " TOOL

# --- Question 2: What freedom means ---
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM

# --- Question 3: What they would build and share ---
read -p "  3. Name one thing you would build and share freely: " BUILD

echo ""
echo "--------------------------------------------------------------"
echo "  Generating your manifesto..."
echo "--------------------------------------------------------------"
echo ""

# --- Gather metadata ---
DATE=$(date '+%d %B %Y')        # e.g. 15 March 2025
TIME=$(date '+%H:%M:%S')        # Current time
AUTHOR=$(whoami)                # Username of the person running the script

# --- Compose the manifesto using string concatenation ---
# Each echo >> appends a new line to the output file
# Using > first to create/overwrite the file, then >> to append

# Write the header
echo "==============================================================" > "$OUTPUT"
echo "  OPEN SOURCE MANIFESTO" >> "$OUTPUT"
echo "  Generated by: $AUTHOR | Date: $DATE | Time: $TIME" >> "$OUTPUT"
echo "==============================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Compose the manifesto paragraph ---
# String concatenation happens as we build the paragraph section by section
MANIFESTO_LINE1="I, $AUTHOR, believe in the power of open-source software."
MANIFESTO_LINE2="Every day, I rely on $TOOL — a tool I did not pay for,"
MANIFESTO_LINE3="did not build alone, and do not own exclusively."
MANIFESTO_LINE4="To me, $FREEDOM is what open source truly means:"
MANIFESTO_LINE5="the freedom to use, study, modify, and share without restriction."

# Write the paragraph to the file
echo "  $MANIFESTO_LINE1" >> "$OUTPUT"
echo "  $MANIFESTO_LINE2" >> "$OUTPUT"
echo "  $MANIFESTO_LINE3" >> "$OUTPUT"
echo "  $MANIFESTO_LINE4" >> "$OUTPUT"
echo "  $MANIFESTO_LINE5" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Second paragraph — their personal pledge
echo "  I pledge that if I ever build something that others could use," >> "$OUTPUT"
echo "  I will share it freely. My first contribution will be $BUILD." >> "$OUTPUT"
echo "  Not because I am required to, but because I have benefited" >> "$OUTPUT"
echo "  from the labor of strangers who never asked for anything in return." >> "$OUTPUT"
echo "  Standing on the shoulders of giants means having the decency" >> "$OUTPUT"
echo "  to lift others when I can." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Closing signature
echo "  — $AUTHOR" >> "$OUTPUT"
echo "    $DATE" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "==============================================================" >> "$OUTPUT"

# --- Confirmation message ---
echo "  Manifesto saved to: $OUTPUT"
echo ""

# --- Display the finished manifesto using cat ---
echo "--------------------------------------------------------------"
echo "  YOUR MANIFESTO:"
echo "--------------------------------------------------------------"
cat "$OUTPUT"
echo ""
echo "=============================================================="
echo "  'Given enough eyeballs, all bugs are shallow.' — Linus's Law"
echo "=============================================================="
